
def ask_for_location():
    print("Hello and welcome to the Weather App")
    print("Please enter the city name, state code and country code")
    data_list = []
    data_list.append(input("Enter the city name: "))
    data_list.append(input("Enter the state code: "))
    data_list.append(input("Enter the country code: ")) 
    return data_list

def show_weather_data(weather_data):
    print(f"### Weather Data for {weather_data['name']}")
    print(f"- **Coordinates**:")
    print(f"  - **Longitude**: {weather_data['coord']['lon']}")
    print(f"  - **Latitude**: {weather_data['coord']['lat']}")
    print()
    print(f"- **Weather**:")
    print(f"  - **Condition**: {weather_data['weather'][0]['main']}")
    print(f"  - **Description**: {weather_data['weather'][0]['description']}")
    
    print()
    print(f"- **Temperature**:")
    print(f"  - **Current**: {weather_data['main']['temp']} K")
    print(f"  - **Feels Like**: {weather_data['main']['feels_like']} K")
    print(f"  - **Minimum**: {weather_data['main']['temp_min']} K")
    print(f"  - **Maximum**: {weather_data['main']['temp_max']} K")
    print()
    print(f"- **Pressure**:")
    print(f"  - **At Sea Level**: {weather_data['main']['sea_level']} hPa")
    print(f"  - **At Ground Level**: {weather_data['main']['grnd_level']} hPa")
    print()
    print(f"- **Humidity**: {weather_data['main']['humidity']}%")
    print()
    print(f"- **Visibility**: {weather_data['visibility']} meters")
    print()
    print(f"- **Wind**:")
    print(f"  - **Speed**: {weather_data['wind']['speed']} m/s")
    print(f"  - **Direction**: {weather_data['wind']['deg']}° (from the west)")
    print(f"  - **Gust**: {weather_data['wind']['gust']} m/s")
    print()
    print(f"- **Cloud Coverage**: {weather_data['clouds']['all']}%")
    print()
    print(f"- **Sunrise**: {weather_data['sys']['sunrise']} (Unix timestamp)")
    print(f"- **Sunset**: {weather_data['sys']['sunset']} (Unix timestamp)")
    print()
    print(f"- **Timezone**: GMT+{weather_data['timezone'] // 3600}")
    print()
    print(f"### Current Location:")
    print(f"- **Name**: {weather_data['name']}")
    print(f"- **Country**: {weather_data['sys']['country']}")
    print()
    print(f"### Data provided by OpenWeatherMap")

